import { Geist, Geist_Mono } from "next/font/google";                 
import "bootstrap/dist/css/bootstrap.min.css"; 
import "./globals.css";
import Header from "../components/Header/Header";
import Bootstrap from "../components/Bootstrap";
import Footer from "../components/Footer/Footer";
// import { useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Bootstrap/>
        {<Header />}
        {children}
       { <Footer/>}
      </body>
    </html>
  );
}
